


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."courses" (
    "id" bigint NOT NULL,
    "name" "text" NOT NULL,
    "state" "text",
    "city" "text",
    "holes" integer,
    "access" "text",
    "course_list_id" bigint NOT NULL
);


ALTER TABLE "public"."courses" OWNER TO "postgres";


COMMENT ON TABLE "public"."courses" IS 'Courses that someone has currently played';



ALTER TABLE "public"."courses" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Courses_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."rounds" (
    "id" bigint NOT NULL,
    "date" "date" NOT NULL,
    "score" bigint
);


ALTER TABLE "public"."rounds" OWNER TO "postgres";


ALTER TABLE "public"."rounds" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Rounds_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_images" (
    "id" bigint NOT NULL,
    "course_id" bigint NOT NULL,
    "path" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."course_images" OWNER TO "postgres";


COMMENT ON TABLE "public"."course_images" IS 'Table for all pictures that are unique to each course';



ALTER TABLE "public"."course_images" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."course_images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."course_list" (
    "id" bigint NOT NULL,
    "name" "text",
    "city" "text",
    "state" "text",
    "holes" bigint,
    "access" "text"
);


ALTER TABLE "public"."course_list" OWNER TO "postgres";


COMMENT ON TABLE "public"."course_list" IS 'List of every course in America';



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "Courses_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."rounds"
    ADD CONSTRAINT "Rounds_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_images"
    ADD CONSTRAINT "course_images_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."course_list"
    ADD CONSTRAINT "course_list_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "courses_course_list_id_key" UNIQUE ("course_list_id");



ALTER TABLE ONLY "public"."courses"
    ADD CONSTRAINT "Courses_course_list_id_fkey" FOREIGN KEY ("course_list_id") REFERENCES "public"."course_list"("id");



CREATE POLICY "Enable insert for authenticated users only" ON "public"."courses" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() = '2b8ce87d-efe9-478d-84d0-2ceb00c7ed31'::"uuid"));



CREATE POLICY "Enable read access for all users" ON "public"."course_list" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."courses" FOR SELECT USING (true);



ALTER TABLE "public"."course_images" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."course_list" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."courses" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."rounds" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON TABLE "public"."courses" TO "anon";
GRANT ALL ON TABLE "public"."courses" TO "authenticated";
GRANT ALL ON TABLE "public"."courses" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Courses_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Courses_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Courses_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."rounds" TO "anon";
GRANT ALL ON TABLE "public"."rounds" TO "authenticated";
GRANT ALL ON TABLE "public"."rounds" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Rounds_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Rounds_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Rounds_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_images" TO "anon";
GRANT ALL ON TABLE "public"."course_images" TO "authenticated";
GRANT ALL ON TABLE "public"."course_images" TO "service_role";



GRANT ALL ON SEQUENCE "public"."course_images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."course_images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."course_images_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."course_list" TO "anon";
GRANT ALL ON TABLE "public"."course_list" TO "authenticated";
GRANT ALL ON TABLE "public"."course_list" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







