drop policy "Enable read access for all users" on "public"."Courses";

revoke delete on table "public"."Courses" from "anon";

revoke insert on table "public"."Courses" from "anon";

revoke references on table "public"."Courses" from "anon";

revoke select on table "public"."Courses" from "anon";

revoke trigger on table "public"."Courses" from "anon";

revoke truncate on table "public"."Courses" from "anon";

revoke update on table "public"."Courses" from "anon";

revoke delete on table "public"."Courses" from "authenticated";

revoke insert on table "public"."Courses" from "authenticated";

revoke references on table "public"."Courses" from "authenticated";

revoke select on table "public"."Courses" from "authenticated";

revoke trigger on table "public"."Courses" from "authenticated";

revoke truncate on table "public"."Courses" from "authenticated";

revoke update on table "public"."Courses" from "authenticated";

revoke delete on table "public"."Courses" from "service_role";

revoke insert on table "public"."Courses" from "service_role";

revoke references on table "public"."Courses" from "service_role";

revoke select on table "public"."Courses" from "service_role";

revoke trigger on table "public"."Courses" from "service_role";

revoke truncate on table "public"."Courses" from "service_role";

revoke update on table "public"."Courses" from "service_role";

revoke delete on table "public"."Rounds" from "anon";

revoke insert on table "public"."Rounds" from "anon";

revoke references on table "public"."Rounds" from "anon";

revoke select on table "public"."Rounds" from "anon";

revoke trigger on table "public"."Rounds" from "anon";

revoke truncate on table "public"."Rounds" from "anon";

revoke update on table "public"."Rounds" from "anon";

revoke delete on table "public"."Rounds" from "authenticated";

revoke insert on table "public"."Rounds" from "authenticated";

revoke references on table "public"."Rounds" from "authenticated";

revoke select on table "public"."Rounds" from "authenticated";

revoke trigger on table "public"."Rounds" from "authenticated";

revoke truncate on table "public"."Rounds" from "authenticated";

revoke update on table "public"."Rounds" from "authenticated";

revoke delete on table "public"."Rounds" from "service_role";

revoke insert on table "public"."Rounds" from "service_role";

revoke references on table "public"."Rounds" from "service_role";

revoke select on table "public"."Rounds" from "service_role";

revoke trigger on table "public"."Rounds" from "service_role";

revoke truncate on table "public"."Rounds" from "service_role";

revoke update on table "public"."Rounds" from "service_role";

alter table "public"."Courses" drop constraint "Courses_pkey";

alter table "public"."Rounds" drop constraint "Rounds_pkey";

drop index if exists "public"."Courses_pkey";

drop index if exists "public"."Rounds_pkey";

drop table "public"."Courses";

drop table "public"."Rounds";


  create table "public"."courses" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "state" text,
    "city" text,
    "holes" integer,
    "access" text,
    "course_list_id" bigint
      );


alter table "public"."courses" enable row level security;


  create table "public"."rounds" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "score" bigint
      );


alter table "public"."rounds" enable row level security;

CREATE UNIQUE INDEX "Courses_pkey" ON public.courses USING btree (id);

CREATE UNIQUE INDEX "Rounds_pkey" ON public.rounds USING btree (id);

alter table "public"."courses" add constraint "Courses_pkey" PRIMARY KEY using index "Courses_pkey";

alter table "public"."rounds" add constraint "Rounds_pkey" PRIMARY KEY using index "Rounds_pkey";

alter table "public"."courses" add constraint "Courses_course_list_id_fkey" FOREIGN KEY (course_list_id) REFERENCES public.course_list(id) not valid;

alter table "public"."courses" validate constraint "Courses_course_list_id_fkey";

grant delete on table "public"."courses" to "anon";

grant insert on table "public"."courses" to "anon";

grant references on table "public"."courses" to "anon";

grant select on table "public"."courses" to "anon";

grant trigger on table "public"."courses" to "anon";

grant truncate on table "public"."courses" to "anon";

grant update on table "public"."courses" to "anon";

grant delete on table "public"."courses" to "authenticated";

grant insert on table "public"."courses" to "authenticated";

grant references on table "public"."courses" to "authenticated";

grant select on table "public"."courses" to "authenticated";

grant trigger on table "public"."courses" to "authenticated";

grant truncate on table "public"."courses" to "authenticated";

grant update on table "public"."courses" to "authenticated";

grant delete on table "public"."courses" to "service_role";

grant insert on table "public"."courses" to "service_role";

grant references on table "public"."courses" to "service_role";

grant select on table "public"."courses" to "service_role";

grant trigger on table "public"."courses" to "service_role";

grant truncate on table "public"."courses" to "service_role";

grant update on table "public"."courses" to "service_role";

grant delete on table "public"."rounds" to "anon";

grant insert on table "public"."rounds" to "anon";

grant references on table "public"."rounds" to "anon";

grant select on table "public"."rounds" to "anon";

grant trigger on table "public"."rounds" to "anon";

grant truncate on table "public"."rounds" to "anon";

grant update on table "public"."rounds" to "anon";

grant delete on table "public"."rounds" to "authenticated";

grant insert on table "public"."rounds" to "authenticated";

grant references on table "public"."rounds" to "authenticated";

grant select on table "public"."rounds" to "authenticated";

grant trigger on table "public"."rounds" to "authenticated";

grant truncate on table "public"."rounds" to "authenticated";

grant update on table "public"."rounds" to "authenticated";

grant delete on table "public"."rounds" to "service_role";

grant insert on table "public"."rounds" to "service_role";

grant references on table "public"."rounds" to "service_role";

grant select on table "public"."rounds" to "service_role";

grant trigger on table "public"."rounds" to "service_role";

grant truncate on table "public"."rounds" to "service_role";

grant update on table "public"."rounds" to "service_role";


  create policy "Enable read access for all users"
  on "public"."courses"
  as permissive
  for select
  to public
using (true);



