drop extension if exists "pg_net";


  create table "public"."Courses" (
    "id" bigint generated by default as identity not null,
    "name" text not null,
    "state" text,
    "city" text
      );


alter table "public"."Courses" enable row level security;


  create table "public"."Rounds" (
    "id" bigint generated by default as identity not null,
    "date" date not null,
    "score" bigint
      );


alter table "public"."Rounds" enable row level security;

CREATE UNIQUE INDEX "Courses_pkey" ON public."Courses" USING btree (id);

CREATE UNIQUE INDEX "Rounds_pkey" ON public."Rounds" USING btree (id);

alter table "public"."Courses" add constraint "Courses_pkey" PRIMARY KEY using index "Courses_pkey";

alter table "public"."Rounds" add constraint "Rounds_pkey" PRIMARY KEY using index "Rounds_pkey";

grant delete on table "public"."Courses" to "anon";

grant insert on table "public"."Courses" to "anon";

grant references on table "public"."Courses" to "anon";

grant select on table "public"."Courses" to "anon";

grant trigger on table "public"."Courses" to "anon";

grant truncate on table "public"."Courses" to "anon";

grant update on table "public"."Courses" to "anon";

grant delete on table "public"."Courses" to "authenticated";

grant insert on table "public"."Courses" to "authenticated";

grant references on table "public"."Courses" to "authenticated";

grant select on table "public"."Courses" to "authenticated";

grant trigger on table "public"."Courses" to "authenticated";

grant truncate on table "public"."Courses" to "authenticated";

grant update on table "public"."Courses" to "authenticated";

grant delete on table "public"."Courses" to "service_role";

grant insert on table "public"."Courses" to "service_role";

grant references on table "public"."Courses" to "service_role";

grant select on table "public"."Courses" to "service_role";

grant trigger on table "public"."Courses" to "service_role";

grant truncate on table "public"."Courses" to "service_role";

grant update on table "public"."Courses" to "service_role";

grant delete on table "public"."Rounds" to "anon";

grant insert on table "public"."Rounds" to "anon";

grant references on table "public"."Rounds" to "anon";

grant select on table "public"."Rounds" to "anon";

grant trigger on table "public"."Rounds" to "anon";

grant truncate on table "public"."Rounds" to "anon";

grant update on table "public"."Rounds" to "anon";

grant delete on table "public"."Rounds" to "authenticated";

grant insert on table "public"."Rounds" to "authenticated";

grant references on table "public"."Rounds" to "authenticated";

grant select on table "public"."Rounds" to "authenticated";

grant trigger on table "public"."Rounds" to "authenticated";

grant truncate on table "public"."Rounds" to "authenticated";

grant update on table "public"."Rounds" to "authenticated";

grant delete on table "public"."Rounds" to "service_role";

grant insert on table "public"."Rounds" to "service_role";

grant references on table "public"."Rounds" to "service_role";

grant select on table "public"."Rounds" to "service_role";

grant trigger on table "public"."Rounds" to "service_role";

grant truncate on table "public"."Rounds" to "service_role";

grant update on table "public"."Rounds" to "service_role";


